repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types: [python]
        exclude: ^src/my_coding_agent/_version\.py$

      - id: ruff-check
        name: ruff-check
        entry: ruff check --fix
        language: system
        types: [python]
        exclude: ^src/my_coding_agent/_version\.py$

      # Temporarily disabled pytest hook due to failing tests needing environment variables
      # TODO: Re-enable after fixing test environment issues
      # - id: pytest
      #   name: pytest
      #   entry: python -m pytest tests/unit/ -q --tb=line
      #   language: system
      #   pass_filenames: false
      #   always_run: true

      # TODO: Enable MyPy after adding comprehensive type annotations
      # - id: mypy
      #   name: mypy
      #   entry: mypy src/ tests/
      #   language: system
      #   types: [python]
      #   pass_filenames: false
      #   always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
