name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies for PyQt6
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libegl1 \
          libxkbcommon-x11-0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-xinerama0 \
          libfontconfig1 \
          libxcb-xfixes0 \
          libxcb-cursor0 \
          libgl1-mesa-dri \
          libglib2.0-0 \
          xvfb

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,test]

    - name: Run pre-commit hooks
      if: matrix.python-version == '3.11'
      run: |
        pip install pre-commit
        pre-commit run --all-files --config .pre-commit-config-ci.yaml

    # TODO: Enable type checking after adding comprehensive type annotations
    # - name: Run type checking
    #   run: mypy .

    - name: Run tests
      run: xvfb-run -a pytest tests/ --cov=my_coding_agent --cov-report=xml --ignore=tests/integration/
      env:
        QT_QPA_PLATFORM: offscreen

    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.11'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
